baseURL = '/'
languageCode = 'es-es'
title = 'arboldemelones blog'
theme = 'notrack'

[params]
author = 'Juan José López Castilla'
# optional, defaults to author:
# siteHeading = '<the text that goes at the top of your webpage>'